query GET_EXERCISES {
  exercises {
    id
    name
  }
}
query GET_EXERCISE($id: String!) {
  exercise(id: $id) {
    id
    name
    description
    patterns {
      id
      name
      score
      description
      bestTempo
      fastestTempo
      goalTempo
      startTempo
    }
  }
}

mutation CREATE_EXERCISE($name: String!, $description: String) {
  createExercise(name: $name, description: $description) {
    id
  }
}

mutation DELETE_EXERCISE($exerciseId: Int!) {
  deleteExercise(exerciseId: $exerciseId) {
    id
  }
}

mutation RENAME_EXERCISE($id: String!, $name: String) {
  updateExercise(id: $id, name: $name) {
    id
  }
}
