mutation DELETE_PATTERN($patternId: Int!) {
  deletePattern(patternId: $patternId) {
    id
  }
}

mutation CREATE_PATTERN($name: String!, $score: String!, $description: String) {
  createPattern(name: $name, score: $score, description: $description) {
    id
  }
}
