query GET_PATTERNS {
  patterns {
    id
    name
    score
    bestTempo
    fastestTempo
  }
}
query GET_PATTERN($id: String!) {
  pattern(id: $id) {
    id
    name
    description
    score
    bestTempo
    goalTempo
    fastestTempo
  }
}

mutation CREATE_PATTERN(
  $name: String!
  $score: String!
  $description: String
  $startTempo: Int
  $goalTempo: Int
  $exerciseId: Int
) {
  createPattern(
    name: $name
    score: $score
    description: $description
    exerciseId: $exerciseId
    startTempo: $startTempo
    goalTempo: $goalTempo
  ) {
    id
  }
}

mutation UPDATE_PATTERN_BEST_TEMPO($id: String!, $tempo: Int!) {
  updatePattern(id: $id, tempo: $tempo) {
    id
  }
}

mutation UPDATE_PATTERN(
  $id: String!
  $name: String!
  $score: String!
  $description: String
  $startTempo: Int
  $goalTempo: Int
) {
  updatePattern(
    id: $id
    name: $name
    score: $score
    description: $description
    startTempo: $startTempo
    goalTempo: $goalTempo
  ) {
    id
  }
}

mutation RENAME_PATTERN($id: String!, $name: String) {
  updatePattern(id: $id, name: $name) {
    id
    name
  }
}

mutation DELETE_PATTERN($patternId: Int!) {
  deletePattern(patternId: $patternId) {
    id
  }
}
