query GET_PATTERNS {
  patterns {
    id
    name
    score
    bestTempo
  }
}
query GET_PATTERN($id: String!) {
  pattern(id: $id) {
    id
    name
    description
    score
    bestTempo
  }
}

mutation CREATE_PATTERN($name: String!, $score: String!, $description: String) {
  createPattern(name: $name, score: $score, description: $description) {
    id
  }
}

mutation UPDATE_PATTERN_BEST_TEMPO($id: String!, $tempo: Int!) {
  updatePattern(id: $id, tempo: $tempo) {
    id
  }
}

mutation DELETE_PATTERN($patternId: String!) {
  deletePattern(patternId: $patternId) {
    id
  }
}
