mutation CREATE_RECORD($tempo: Int!, $rating: Int!, $patternId: String!) {
  createRecord(tempo: $tempo, rating: $rating, patternId: $patternId) {
    id
    createdAt
  }
}

mutation DELETE_RECORD($recordId: Int!) {
  deleteRecord(recordId: $recordId) {
    id
  }
}
